# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on:  [self-hosted, Hosting]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create docker image and tar file
        run: |
         docker build -t api.bonch.fun .
         docker save -o api.bonch.fun.tar api.bonch.fun
        
#       - name: 'Upload Artifact'
#         uses: actions/upload-artifact@v2
#         with:
#           name: docker_image_tar
#           path: api.bonch.fun.tar

      - name: Load docker image to backend server
        run: | 
         scp -P ${{ secrets.BACKEND_SSH_PORT }} deploy@${{ secrets.BACKEND_SSH_HOSTNAME }}:/home/deploy/api.bonch.fun/ api.bonch.fun.tar
  
  deploy:
    runs-on:  [self-hosted, Home]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       - name: Load docker image to local register
         run: echo "ff"
